apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: ensure-image-from-trusted-registry
  namespace: girus
spec:
  validationFailureAction: Enforce
  rules:
    - name: ensure-image-from-trusted-registry
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "All container images must be pulled from the trusted registry 'docker.io'."
        pattern:
          spec:
            containers:
              - image: "docker.io/henriquezimermann/*"
